In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [4]:
a1 = np.array([[1,2,3,4],
              [5,6,7,8]])
a1.size

8

In [5]:
a1.shape

(2, 4)

In [6]:
np.zeros([2,4],dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
np.ones([2,3],dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
np.arange(0,20,2,dtype = int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.full((2,6),11)

array([[11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11]])

In [11]:
np.linspace(2,10,20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [16]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [17]:
np.random.random((4,4))

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [18]:
np.random.normal(0,1,(3,3))

array([[ 2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575]])

In [19]:
np.random.randint(2,20,(4,5))

array([[ 3,  9, 11,  5,  8],
       [13, 16,  2, 16,  5],
       [14, 12, 13,  6,  8],
       [ 6, 17,  5, 14,  6]])

In [23]:
np.random.rand(3,4)

array([[0.58185033, 0.41436859, 0.4746975 , 0.6235101 ],
       [0.33800761, 0.67475232, 0.31720174, 0.77834548],
       [0.94957105, 0.66252687, 0.01357164, 0.6228461 ]])

In [24]:
x1 = np.random.randint(20,size = 6)

In [25]:
x1

array([ 4,  2, 16,  3,  2, 10])

In [28]:
x1[3],x1[5],x1[2]

(3, 10, 16)

In [29]:
x2 = np.random.randint(0,20,size = (3,4))

In [30]:
x2

array([[13, 16,  7,  9],
       [ 0, 10, 18, 11],
       [ 2,  2,  3,  3]])

In [31]:
x2[1,2],x2[0,3],x2[2,1]

(18, 9, 2)

In [32]:
x1[3] = 4

In [33]:
x1

array([ 4,  2, 16,  4,  2, 10])

In [34]:
x2[1,2] = 19

In [35]:
x2

array([[13, 16,  7,  9],
       [ 0, 10, 19, 11],
       [ 2,  2,  3,  3]])

In [36]:
x1

array([ 4,  2, 16,  4,  2, 10])

In [37]:
x1[:3]

array([ 4,  2, 16])

In [38]:
x1[2:6]

array([16,  4,  2, 10])

In [39]:
x1[::2]

array([ 4, 16,  2])

In [41]:
x1[-2::-1]

array([ 2,  4, 16,  2,  4])

In [42]:
x2

array([[13, 16,  7,  9],
       [ 0, 10, 19, 11],
       [ 2,  2,  3,  3]])

In [43]:
x2[:2,1:]

array([[16,  7,  9],
       [10, 19, 11]])

In [44]:
x1[2]

16

In [45]:
a = np.arange(0,20,2)

In [46]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
a.shape

(10,)

In [49]:
a.reshape([2,5])

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [50]:
a.shape

(10,)

In [51]:
a.reshape([2,5])

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [52]:
a.reshape([2,5]).shape

(2, 5)

In [54]:
a.reshape([10,1])

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [55]:
a.reshape([10,1]).shape

(10, 1)

In [56]:
b = a.reshape([2,5])

In [57]:
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [58]:
b.T

array([[ 0, 10],
       [ 2, 12],
       [ 4, 14],
       [ 6, 16],
       [ 8, 18]])

In [63]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [64]:
y = np.array([[1,2,3],
              [4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.concatenate((y,y))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
y = np.array([1,2,3])
x = np.array([1,2,3])

In [75]:
np.concatenate((x,x))

array([1, 2, 3, 1, 2, 3])

In [ ]:
y = np.array([[1,2,3],
              [4,5,6]])

In [76]:
np.concatenate((y,y),axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])